apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-game-backend
  labels:
    app: word-game-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: word-game-backend
  template:
    metadata:
      labels:
        app: word-game-backend
    spec:
      containers:
        - name: word-game-backend
          image: jhedie/word-game-backend:v0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
