apiVersion: v1
kind: Service
metadata:
  name: word-game-backend-service
spec:
  selector:
    app: word-game-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
