apiVersion: v1
kind: Service
metadata:
  name: word-game-frontend-service
spec:
  selector:
    app: word-game-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
